import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const unitTemplates = [
  // SPACE MARINES - 10th Edition
  {
    name: 'Intercessor Squad',
    faction: 'Space Marines',
    role: 'Battleline',
    basePointsCost: 95,
    movement: '6"',
    toughness: 4,
    save: '3+',
    wounds: 2,
    leadership: 6,
    objectiveControl: 2,
    keywords: JSON.stringify(['INFANTRY', 'BATTLELINE', 'IMPERIUM', 'TACTICUS', 'INTERCESSOR SQUAD']),
    abilities: JSON.stringify(['Oath of Moment', 'Bolt Rifle Tactics']),
    wargearOptions: JSON.stringify(['Bolt Rifle', 'Auto Bolt Rifle', 'Stalker Bolt Rifle', 'Astartes Grenade Launcher', 'Power Fist', 'Thunder Hammer']),
    datasheet: 'Intercessor Squad',
    edition: '10th',
  },
  {
    name: 'Tactical Squad',
    faction: 'Space Marines',
    role: 'Battleline',
    basePointsCost: 90,
    movement: '6"',
    toughness: 4,
    save: '3+',
    wounds: 2,
    leadership: 6,
    objectiveControl: 2,
    keywords: JSON.stringify(['INFANTRY', 'BATTLELINE', 'IMPERIUM', 'TACTICAL SQUAD']),
    abilities: JSON.stringify(['Oath of Moment', 'Tactical Flexibility']),
    wargearOptions: JSON.stringify(['Boltgun', 'Flamer', 'Meltagun', 'Plasma Gun', 'Heavy Bolter', 'Missile Launcher', 'Power Weapon', 'Power Fist']),
    datasheet: 'Tactical Squad',
    edition: '10th',
  },
  {
    name: 'Captain',
    faction: 'Space Marines',
    role: 'Character',
    basePointsCost: 80,
    movement: '6"',
    toughness: 4,
    save: '3+',
    wounds: 5,
    leadership: 6,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'CHARACTER', 'IMPERIUM', 'CAPTAIN', 'OFFICER']),
    abilities: JSON.stringify(['Oath of Moment', 'Rites of Battle', 'Leader']),
    wargearOptions: JSON.stringify(['Master-crafted Boltgun', 'Power Sword', 'Power Fist', 'Thunder Hammer', 'Relic Shield', 'Plasma Pistol']),
    datasheet: 'Captain',
    edition: '10th',
  },
  {
    name: 'Librarian',
    faction: 'Space Marines',
    role: 'Character',
    basePointsCost: 75,
    movement: '6"',
    toughness: 4,
    save: '3+',
    wounds: 4,
    leadership: 6,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'CHARACTER', 'PSYKER', 'IMPERIUM', 'LIBRARIAN']),
    abilities: JSON.stringify(['Oath of Moment', 'Psychic Hood', 'Leader', 'Smite', 'Psychic Powers']),
    wargearOptions: JSON.stringify(['Force Weapon', 'Bolt Pistol', 'Plasma Pistol']),
    datasheet: 'Librarian',
    edition: '10th',
  },
  {
    name: 'Terminator Squad',
    faction: 'Space Marines',
    role: 'Elites',
    basePointsCost: 200,
    movement: '5"',
    toughness: 5,
    save: '2+',
    wounds: 3,
    leadership: 6,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'IMPERIUM', 'TERMINATOR', 'TERMINATOR SQUAD']),
    abilities: JSON.stringify(['Oath of Moment', 'Terminator Armour', 'Deep Strike', 'Crux Terminatus']),
    wargearOptions: JSON.stringify(['Storm Bolter', 'Power Fist', 'Lightning Claws', 'Thunder Hammer', 'Storm Shield', 'Assault Cannon', 'Heavy Flamer', 'Cyclone Missile Launcher']),
    datasheet: 'Terminator Squad',
    edition: '10th',
  },
  {
    name: 'Dreadnought',
    faction: 'Space Marines',
    role: 'Elites',
    basePointsCost: 140,
    movement: '6"',
    toughness: 9,
    save: '2+',
    wounds: 8,
    leadership: 6,
    objectiveControl: 3,
    keywords: JSON.stringify(['VEHICLE', 'WALKER', 'IMPERIUM', 'DREADNOUGHT']),
    abilities: JSON.stringify(['Oath of Moment', 'Duty Eternal']),
    wargearOptions: JSON.stringify(['Multi-melta', 'Twin Lascannon', 'Assault Cannon', 'Heavy Flamer', 'Missile Launcher', 'Dreadnought Combat Weapon']),
    datasheet: 'Dreadnought',
    edition: '10th',
  },
  {
    name: 'Predator',
    faction: 'Space Marines',
    role: 'Heavy Support',
    basePointsCost: 130,
    movement: '10"',
    toughness: 10,
    save: '3+',
    wounds: 11,
    leadership: 6,
    objectiveControl: 3,
    keywords: JSON.stringify(['VEHICLE', 'IMPERIUM', 'PREDATOR']),
    abilities: JSON.stringify(['Oath of Moment', 'Armoured Superiority']),
    wargearOptions: JSON.stringify(['Predator Autocannon', 'Twin Lascannon', 'Heavy Bolter Sponsons', 'Lascannon Sponsons', 'Storm Bolter', 'Hunter-killer Missile']),
    datasheet: 'Predator',
    edition: '10th',
  },
  {
    name: 'Assault Squad',
    faction: 'Space Marines',
    role: 'Fast Attack',
    basePointsCost: 100,
    movement: '12"',
    toughness: 4,
    save: '3+',
    wounds: 2,
    leadership: 6,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'FLY', 'JUMP PACK', 'IMPERIUM', 'ASSAULT SQUAD']),
    abilities: JSON.stringify(['Oath of Moment', 'Hammer of Wrath']),
    wargearOptions: JSON.stringify(['Bolt Pistol', 'Chainsword', 'Plasma Pistol', 'Flamer', 'Plasma Gun', 'Power Weapon', 'Thunder Hammer']),
    datasheet: 'Assault Squad',
    edition: '10th',
  },
  
  // TYRANIDS - 10th Edition
  {
    name: 'Termagants',
    faction: 'Tyranids',
    role: 'Battleline',
    basePointsCost: 60,
    movement: '6"',
    toughness: 3,
    save: '5+',
    wounds: 1,
    leadership: 8,
    objectiveControl: 2,
    keywords: JSON.stringify(['INFANTRY', 'BATTLELINE', 'TYRANIDS', 'ENDLESS SWARM', 'TERMAGANTS']),
    abilities: JSON.stringify(['Synapse', 'Scuttling Swarm']),
    wargearOptions: JSON.stringify(['Fleshborer', 'Devourer', 'Spinefists']),
    datasheet: 'Termagants',
    edition: '10th',
  },
  {
    name: 'Hormagaunts',
    faction: 'Tyranids',
    role: 'Battleline',
    basePointsCost: 65,
    movement: '8"',
    toughness: 3,
    save: '5+',
    wounds: 1,
    leadership: 8,
    objectiveControl: 2,
    keywords: JSON.stringify(['INFANTRY', 'BATTLELINE', 'TYRANIDS', 'ENDLESS SWARM', 'HORMAGAUNTS']),
    abilities: JSON.stringify(['Synapse', 'Bounding Leap']),
    wargearOptions: JSON.stringify(['Scything Talons', 'Adrenal Glands']),
    datasheet: 'Hormagaunts',
    edition: '10th',
  },
  {
    name: 'Tyranid Warriors',
    faction: 'Tyranids',
    role: 'Elites',
    basePointsCost: 100,
    movement: '6"',
    toughness: 5,
    save: '4+',
    wounds: 3,
    leadership: 7,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'SYNAPSE', 'TYRANIDS', 'TYRANID WARRIORS']),
    abilities: JSON.stringify(['Synapse', 'Shadow in the Warp']),
    wargearOptions: JSON.stringify(['Deathspitter', 'Devourer', 'Barbed Strangler', 'Venom Cannon', 'Scything Talons', 'Boneswords', 'Lash Whip and Bonesword']),
    datasheet: 'Tyranid Warriors',
    edition: '10th',
  },
  {
    name: 'Hive Tyrant',
    faction: 'Tyranids',
    role: 'Character',
    basePointsCost: 220,
    movement: '8"',
    toughness: 9,
    save: '2+',
    wounds: 10,
    leadership: 7,
    objectiveControl: 3,
    keywords: JSON.stringify(['MONSTER', 'CHARACTER', 'SYNAPSE', 'TYRANIDS', 'HIVE TYRANT']),
    abilities: JSON.stringify(['Synapse', 'Shadow in the Warp', 'Hive Commander']),
    wargearOptions: JSON.stringify(['Heavy Venom Cannon', 'Stranglethorn Cannon', 'Scything Talons', 'Monstrous Boneswords', 'Lash Whip and Monstrous Bonesword']),
    datasheet: 'Hive Tyrant',
    edition: '10th',
  },
  {
    name: 'Carnifex',
    faction: 'Tyranids',
    role: 'Heavy Support',
    basePointsCost: 125,
    movement: '6"',
    toughness: 10,
    save: '2+',
    wounds: 10,
    leadership: 8,
    objectiveControl: 3,
    keywords: JSON.stringify(['MONSTER', 'TYRANIDS', 'CARNIFEX']),
    abilities: JSON.stringify(['Synapse', 'Living Battering Ram', 'Spore Cysts']),
    wargearOptions: JSON.stringify(['Deathspitter', 'Devourer', 'Heavy Venom Cannon', 'Stranglethorn Cannon', 'Scything Talons', 'Crushing Claws', 'Monstrous Scything Talons']),
    datasheet: 'Carnifex',
    edition: '10th',
  },
  {
    name: 'Genestealers',
    faction: 'Tyranids',
    role: 'Elites',
    basePointsCost: 85,
    movement: '8"',
    toughness: 4,
    save: '5+',
    wounds: 2,
    leadership: 7,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'TYRANIDS', 'GENESTEALERS']),
    abilities: JSON.stringify(['Synapse', 'Lightning Reflexes', 'Vanguard Invaders']),
    wargearOptions: JSON.stringify(['Scything Talons', 'Rending Claws', 'Acid Maw']),
    datasheet: 'Genestealers',
    edition: '10th',
  },
  {
    name: 'Neurothrope',
    faction: 'Tyranids',
    role: 'Character',
    basePointsCost: 105,
    movement: '6"',
    toughness: 9,
    save: '4+',
    wounds: 9,
    leadership: 7,
    objectiveControl: 2,
    keywords: JSON.stringify(['MONSTER', 'CHARACTER', 'PSYKER', 'SYNAPSE', 'TYRANIDS', 'ZOANTHROPES', 'NEUROTHROPE']),
    abilities: JSON.stringify(['Synapse', 'Shadow in the Warp', 'Warp Blast', 'Psychic Scream']),
    wargearOptions: JSON.stringify(['Psychic Powers']),
    datasheet: 'Neurothrope',
    edition: '10th',
  },
  {
    name: 'Ripper Swarms',
    faction: 'Tyranids',
    role: 'Fast Attack',
    basePointsCost: 20,
    movement: '6"',
    toughness: 3,
    save: '6+',
    wounds: 4,
    leadership: 8,
    objectiveControl: 0,
    keywords: JSON.stringify(['INFANTRY', 'SWARM', 'TYRANIDS', 'RIPPER SWARMS']),
    abilities: JSON.stringify(['Synapse', 'Chittering Hordes']),
    wargearOptions: JSON.stringify(['Claws and Teeth', 'Spinemaws']),
    datasheet: 'Ripper Swarms',
    edition: '10th',
  },
  {
    name: 'Neurotyrant',
    faction: 'Tyranids',
    role: 'Character',
    basePointsCost: 105,
    movement: '6"',
    toughness: 9,
    save: '4+',
    wounds: 9,
    leadership: 7,
    objectiveControl: 2,
    keywords: JSON.stringify(['MONSTER', 'CHARACTER', 'PSYKER', 'SYNAPSE', 'TYRANIDS', 'NEUROTYRANT']),
    abilities: JSON.stringify(['Synapse', 'Shadow in the Warp', 'Psychic Scream', 'Neuronode']),
    wargearOptions: JSON.stringify(['Neurotyrant claws and lashes', 'Psychic scream']),
    datasheet: 'Neurotyrant',
    edition: '10th',
  },
  {
    name: 'The Swarmlord',
    faction: 'Tyranids',
    role: 'Character',
    basePointsCost: 220,
    movement: '8"',
    toughness: 10,
    save: '2+',
    wounds: 12,
    leadership: 7,
    objectiveControl: 4,
    keywords: JSON.stringify(['MONSTER', 'CHARACTER', 'SYNAPSE', 'TYRANIDS', 'EPIC HERO', 'THE SWARMLORD']),
    abilities: JSON.stringify(['Synapse', 'Shadow in the Warp', 'Hive Commander', 'Synaptic Pulse']),
    wargearOptions: JSON.stringify(['Bone sabres', 'Synaptic pulse']),
    datasheet: 'The Swarmlord',
    edition: '10th',
  },
  {
    name: 'Exocrine',
    faction: 'Tyranids',
    role: 'Heavy Support',
    basePointsCost: 140,
    movement: '6"',
    toughness: 11,
    save: '2+',
    wounds: 14,
    leadership: 8,
    objectiveControl: 4,
    keywords: JSON.stringify(['MONSTER', 'TYRANIDS', 'EXOCRINE']),
    abilities: JSON.stringify(['Synapse', 'Symbiotic Targeting', 'Bio-plasmic Barrage']),
    wargearOptions: JSON.stringify(['Bio-plasmic cannon', 'Powerful limbs']),
    datasheet: 'Exocrine',
    edition: '10th',
  },
  {
    name: 'Haruspex',
    faction: 'Tyranids',
    role: 'Heavy Support',
    basePointsCost: 125,
    movement: '8"',
    toughness: 10,
    save: '2+',
    wounds: 10,
    leadership: 8,
    objectiveControl: 3,
    keywords: JSON.stringify(['MONSTER', 'TYRANIDS', 'HARUSPEX']),
    abilities: JSON.stringify(['Synapse', 'Ravenous Appetite', 'Deadly Predator']),
    wargearOptions: JSON.stringify(['Grasping tongue', 'Ravenous maw', 'Shovelling claws']),
    datasheet: 'Haruspex',
    edition: '10th',
  },
  {
    name: 'Lictor',
    faction: 'Tyranids',
    role: 'Elites',
    basePointsCost: 60,
    movement: '8"',
    toughness: 6,
    save: '5+',
    wounds: 6,
    leadership: 7,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'TYRANIDS', 'LICTOR']),
    abilities: JSON.stringify(['Synapse', 'Hidden Hunter', 'Pheromone Trail']),
    wargearOptions: JSON.stringify(['Lictor claws and talons']),
    datasheet: 'Lictor',
    edition: '10th',
  },
  {
    name: 'Raveners',
    faction: 'Tyranids',
    role: 'Fast Attack',
    basePointsCost: 125,
    movement: '10"',
    toughness: 5,
    save: '4+',
    wounds: 3,
    leadership: 8,
    objectiveControl: 1,
    keywords: JSON.stringify(['INFANTRY', 'TYRANIDS', 'RAVENERS']),
    abilities: JSON.stringify(['Synapse', 'Death from Below', 'Ravening Claws']),
    wargearOptions: JSON.stringify(['Ravener claws and talons', 'Deathspitter', 'Spinefists']),
    datasheet: 'Raveners',
    edition: '10th',
  },
  {
    name: 'Tyrannofex',
    faction: 'Tyranids',
    role: 'Heavy Support',
    basePointsCost: 200,
    movement: '8"',
    toughness: 12,
    save: '2+',
    wounds: 16,
    leadership: 8,
    objectiveControl: 5,
    keywords: JSON.stringify(['MONSTER', 'TYRANIDS', 'TYRANNOFEX']),
    abilities: JSON.stringify(['Synapse', 'Impenetrable Chitin', 'Bio-weapon Beast']),
    wargearOptions: JSON.stringify(['Fleshborer hive', 'Stinger salvoes', 'Powerful limbs', 'Acid Spray', 'Rupture Cannon']),
    datasheet: 'Tyrannofex',
    edition: '10th',
  },
];

async function main() {
  console.log('🌟 Seeding unit templates...');
  
  for (const template of unitTemplates) {
    // Generate consistent ID
    const id = template.name.replace(/\s/g, '_').toUpperCase() + '_' + template.faction.replace(/\s/g, '_').toUpperCase();
    
    const created = await prisma.datasheet.upsert({
      where: { id },
      update: template,
      create: {
        id,
        ...template,
      },
    });
    console.log(`✅ Created/Updated: ${created.name} (${created.faction})`);
  }
  
  console.log('✨ Seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });



